export const FETCH_POKEMONS = "FETCH_POKEMONS";
export const ERROR_FETCH_POKEMONS = "ERROR_FETCH_POKEMONS";
export const FETCH_POKEMON = "FETCH_POKEMON";
export const ERROR_FETCH_POKEMON = "ERROR_FETCH_POKEMON";
